package rebalancer

import (
	"log"
	"math"
	"sort"
	"strings"
	"time"
)

// Config holds the configuration for the portfolio rebalancer.
type Config struct {
	Enabled                bool
	TriggerMode            string // "time", "threshold", or "both"
	DriftThresholdPct      float64
	TargetAllocations      map[string]float64
	AvoidWashSales         bool
	RebalanceIntervalHours float64
}

// Order represents an adjustment order generated by the rebalancer.
type Order struct {
	Symbol    string
	Side      string
	AmountUSD float64
}

// Adjustment represents the calculated drift for a symbol.
type Adjustment struct {
	Symbol     string
	CurrentPct float64
	TargetPct  float64
	DriftPct   float64
	DiffUSD    float64
	Action     string
}

// Trade represents a historical trade for wash sale detection.
type Trade struct {
	Symbol    string
	Side      string // "BUY" or "SELL"
	Timestamp time.Time
}

// Rebalancer computes portfolio drift and generates rebalance orders.
type Rebalancer struct {
	config Config
}

// NewRebalancer creates a new Rebalancer instance.
func NewRebalancer(config Config) *Rebalancer {
	return &Rebalancer{config: config}
}

// CheckDrift calculates the drift of the current portfolio from target allocations.
func (r *Rebalancer) CheckDrift(currentPortfolio map[string]float64, totalPortfolioValue float64) []Adjustment {
	targets := r.config.TargetAllocations
	if len(targets) == 0 || totalPortfolioValue <= 0 {
		return nil
	}

	// Ensure targets sum to <= 100%
	var targetSum float64
	for _, v := range targets {
		targetSum += v
	}
	if targetSum > 100.0 {
		log.Printf("[Rebalancer] Target allocations sum > 100%% (%f%%). Normalizing.", targetSum)
		normalized := make(map[string]float64)
		for k, v := range targets {
			normalized[k] = (v / targetSum) * 100.0
		}
		targets = normalized
	}

	var adjustments []Adjustment
	driftThreshold := r.config.DriftThresholdPct

	for symbol, targetPct := range targets {
		currentValue := currentPortfolio[symbol]
		currentPct := (currentValue / totalPortfolioValue) * 100.0

		drift := currentPct - targetPct
		driftAbs := math.Abs(drift)

		if driftAbs >= driftThreshold {
			targetValue := totalPortfolioValue * (targetPct / 100.0)
			diffUSD := targetValue - currentValue

			side := "BUY"
			if diffUSD < 0 {
				side = "SELL"
			}

			adjustments = append(adjustments, Adjustment{
				Symbol:     symbol,
				CurrentPct: currentPct,
				TargetPct:  targetPct,
				DriftPct:   drift,
				DiffUSD:    math.Abs(diffUSD),
				Action:     side,
			})
		}
	}

	return adjustments
}

// IsRebalanceDue checks if a rebalance is due based on the configured time interval.
func (r *Rebalancer) IsRebalanceDue(lastRebalanceTS time.Time) bool {
	mode := strings.ToLower(r.config.TriggerMode)
	if mode != "time" && mode != "both" {
		return false
	}

	interval := time.Duration(r.config.RebalanceIntervalHours * float64(time.Hour))
	return time.Since(lastRebalanceTS) >= interval
}

// isWashSale naive wash sale prevention.
func (r *Rebalancer) isWashSale(symbol string, currentPrice, avgCost float64, tradeHistory []Trade) bool {
	if currentPrice >= avgCost {
		return false // Selling for a profit is not a wash sale
	}

	thirtyDays := 30 * 24 * time.Hour
	now := time.Now()

	for _, trade := range tradeHistory {
		if trade.Symbol == symbol && strings.ToUpper(trade.Side) == "BUY" {
			if now.Sub(trade.Timestamp) <= thirtyDays {
				return true
			}
		}
	}

	return false
}

// GenerateRebalanceOrders takes the detected drift and factors in wash sales to output Orders.
func (r *Rebalancer) GenerateRebalanceOrders(
	currentPortfolio map[string]float64,
	totalValue float64,
	priceData map[string]float64,
	costBasisData map[string]float64,
	tradeHistory []Trade,
) []Order {
	if tradeHistory == nil {
		tradeHistory = []Trade{}
	}

	avoidWashSales := r.config.AvoidWashSales
	adjustments := r.CheckDrift(currentPortfolio, totalValue)

	var orders []Order
	for _, adj := range adjustments {
		symbol := adj.Symbol
		side := adj.Action
		diffUSD := adj.DiffUSD

		if side == "SELL" && avoidWashSales {
			currentPrice := priceData[symbol]
			avgCost := costBasisData[symbol]

			if currentPrice > 0 && avgCost > 0 {
				if r.isWashSale(symbol, currentPrice, avgCost, tradeHistory) {
					log.Printf("[Rebalancer] Wash sale prevented for %s. Current px: %f, Avg cost: %f", symbol, currentPrice, avgCost)
					continue
				}
			}
		}

		orders = append(orders, Order{
			Symbol:    symbol,
			Side:      side,
			AmountUSD: diffUSD,
		})
	}

	// Sort orders so SELLs happen before BUYs (to free up capital)
	sort.Slice(orders, func(i, j int) bool {
		if orders[i].Side == "SELL" && orders[j].Side != "SELL" {
			return true
		}
		if orders[i].Side != "SELL" && orders[j].Side == "SELL" {
			return false
		}
		return orders[i].Symbol < orders[j].Symbol
	})

	return orders
}
